
server:
  port: 8082

logging:
  file:
    name: app.log
  
spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://mysqldb:3306/practice
    username: root
    password: root
    
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true  